### ISSUE TITLE
Doesn't require `--privileged`

### ISSUE THREAD

**Issue by dnwe** [kfei/dockmotion#1]
Firstly, thanks for putting this together - great job.
Secondly, `--privileged` isn't actually required to give the container access to the webcam(s). You can use `--device=/dev/video0` instead.

e.g.,
`docker run -it --device=/dev/video0 -p 8081:8081 -e TIMEZONE="Europe/London" ...` etc.

Might be worth changing in the README

**Comment by kfei** [comment]
@dnwe , many thanks for this! Didn't follow Docker upstream quite a long time. Nice to know the `--device` flag! Now the dangerous `--privileged` flag is no longer required. README updated.
